"""Fix the broken #ifndef/#define guards in static_model.h generated by genmodel."""
import os

path = r"c:\goose\sas_server\static_model.h"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

fixed = 0
for i, line in enumerate(lines):
    if line.strip().startswith("#ifndef") and "GOOSE" in line and "STATIC_MODEL" in line:
        lines[i] = "#ifndef STATIC_MODEL_H_\n"
        fixed += 1
    elif line.strip().startswith("#define") and "GOOSE" in line and "STATIC_MODEL" in line:
        lines[i] = "#define STATIC_MODEL_H_\n"
        fixed += 1

with open(path, "w", encoding="utf-8") as f:
    f.writelines(lines)

print(f"Fixed {fixed} header guard lines in {path}")
